### PR TITLE
dahdi-linux: fix build with kernel 3.15 and newer

### PR DESCRIPTION
**Pull request by dangowrt**
smp_mb__after_clear_bit() was removed from newer kernels.
Use smp_mb__after_atomic() instead.

Spotted on buildbot on targets using kernel 3.18:
.../dahdi-linux-2.10.0.1/drivers/dahdi/wcte13xp-base.c: In function 't13x_set_linemode':
.../dahdi-linux-2.10.0.1/drivers/dahdi/wcte13xp-base.c:1852:2: error: implicit declaration of function 'smp_mb__after_clear_bit' [-Werror=implicit-function-declaration]
  smp_mb__after_clear_bit();
  ^

Signed-off-by: Daniel Golle <daniel@makrotopia.org>

### CODE REVIEW

**Comment by jslachta** [comment]
Thank you for your contribution. Compile and run tested.
